class Draw:
    def drawGallows(self, countOfMistakes):
        if countOfMistakes == 0:
            print(' _____________________________ ')
            print('{         _________           }')
            print('{         |/      |           }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{       __|_________          }')
            print('{_______|__________|__________}')

        if countOfMistakes == 1:
            print(' _____________________________ ')
            print('{         _________           }')
            print('{         |/      |           }')
            print('{         |      (_)          }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{       __|_________          }')
            print('{_______|__________|__________}')

        if countOfMistakes == 2:
            print(' _____________________________ ')
            print('{         _________           }')
            print('{         |/      |           }')
            print('{         |      (_)          }')
            print('{         |       |           }')
            print('{         |       |           }')
            print('{         |       |           }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{       __|_________          }')
            print('{_______|__________|__________}')

        if countOfMistakes == 3:
            print(' _____________________________ ')
            print('{         _________           }')
            print('{         |/      |           }')
            print('{         |      (_)          }')
            print('{         |      _|           }')
            print('{         |     / |           }')
            print('{         |       |           }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{       __|_________          }')
            print('{_______|__________|__________}')

        if countOfMistakes == 4:
            print(' _____________________________ ')
            print('{         _________           }')
            print('{         |/      |           }')
            print('{         |      (_)          }')
            print('{         |      _|_          }')
            print('{         |     / | \         }')
            print('{         |       |           }')
            print('{         |                   }')
            print('{         |                   }')
            print('{         |                   }')
            print('{       __|_________          }')
            print('{_______|__________|__________}')

        if countOfMistakes == 5:
            print(' _____________________________ ')
            print('{         _________           }')
            print('{         |/      |           }')
            print('{         |      (_)          }')
            print('{         |      _|_          }')
            print('{         |     / | \         }')
            print('{         |       |           }')
            print('{         |      /            }')
            print('{         |     /             }')
            print('{         |                   }')
            print('{       __|_________          }')
            print('{_______|__________|__________}')

        if countOfMistakes == 6:
            print(' _____________________________ ')
            print('{         _________           }')
            print('{         |/      |           }')
            print('{         |      (_)          }')
            print('{         |      _|_          }')
            print('{         |     / | \         }')
            print('{         |       |           }')
            print('{         |      / \          }')
            print('{         |     /   \         }')
            print('{         |                   }')
            print('{       __|_________          }')
            print('{_______|__________|__________}')


if __name__ == '__main__':
    draw = Draw()
    draw.drawGallows(3)